version: '3'

networks:
  internal-network:
    driver: bridge   

services:
  db:
    container_name: gitea_db
    image: lsioarmhf/mariadb
    restart: unless-stopped
    networks:
      - internal-network
    volumes:
      - ./data/db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=gitea
    labels:
      traefik.enable: false

  app:
    container_name: gitea_app
    build: .
    #image: your_image_name
    restart: unless-stopped
    networks:      
      - internal-network
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./data/app/data:/data
    environment:
      - DB_TYPE=mysql
      - DB_HOST=gitea_db:3306
      - DB_NAME=gitea
      - DB_USER=root
      - DB_PASSWD=
    depends_on:
      - db